#!/bin/sh

HN=$(hostname)

NC=$(get.site 14 @NUM_CH)
MODE=$(get.site 14 @REF_SOURCE)
NR=$(get.site 14 @NUM_REF)

ALIAS_DB=db/lia-aliases.db
ALIAS_DB2=db/lia-aliases2.db

LEN=${SIZE:-4096}
source ./scripts/record_support.sh

make_real_aliases() {
(
for ch in $(seq 1 $NC); do
	let ch1="($ch-1)*$NR"
	for ref in $(seq 1 $NR); do
		let chn="$ch1+$ref"
		printf "alias(\"$HN:1:AI:WF:%02d\", \"$HN:1:CH%02d:REF%d\")\\n" \
			$chn $ch $ref
		printf "alias(\"$HN:1:AI:WF:%02d:V\", \"$HN:1:CH%02d:REF%d:V\")\\n" \
			$chn $ch $ref
	done
done
)
}

IQ() {
	if [ $1 -eq 0 ]; then
		echo I
	else
		echo Q
	fi
}

make_cplx_aliases() { (
let chn=1
for ch in $(seq 1 $NC); do
	for iq in 0 1; do
		for ref in $(seq 1 $NR); do
			printf "alias(\"$HN:1:AI:WF:%02d\", \
				\"$HN:1:CH%02d:REF%d:%c\")\\n" \
				$chn $ch $ref $(IQ $iq)
			let chn=$chn+1
		done
	done
done
) }

make_cplx_spec() {
let chn=1
for ch in $(seq 1 $NC); do
	for ref in $(seq 1 $NR); do
		cid=$(printf "%02d" $chn)
		pfx=$(printf "$HN:1:CH%02d:REF%d" $ch $ref)
		
		cprams="UUT=$HN,SITE=1,REF=${ref},RS=LONG,PFX=$pfx,cid=$cid,LEN=$LEN,FSB=128"
		echo "dbLoadRecords(\"db/wfComplex.db\",\"$cprams\")"
		let chn=$chn+1
	done
done
}
# acq1001_044:1:AI:WF:FMIXER
make_mixer_alias() {
	echo "alias(\"${HN}:DSP:LIA:REF:FREQ:1\", \"${HN}:1:AI:WF:FMIXER\")"
}

load_lia_aliases() {
cat - <<EOF
dbLoadRecords("$1","")
EOF
}

PRAMS="UUT=$HN,SITE=1,SPORT=S14"

if [ $MODE -ne 0 ]; then
	# echo COMPLEX LIA detected
	make_cplx_aliases > $ALIAS_DB
	load_lia_aliases $ALIAS_DB
	make_cplx_spec
	for ref in $(seq 1 $NR); do
		let ref0=$ref-1
		cprams="${PRAMS},FMIN=1000,FMAX=49000,REF=$ref,REF0=$ref0"
		echo 'dbLoadRecords("db/lia-refs.db","'${cprams}'")'
	done
	make_mixer_alias > $ALIAS_DB2
else
	make_real_aliases > $ALIAS_DB
	load_lia_aliases
	let nrm1="$NR-1"
	for ref in $(seq 1 $NR); do
		let ref0=$ref-1
		cprams="${PRAMS},REF=$ref,REF0=$ref0"
		xprams="${cprams},T=REF_OFFSET,LO=-32767,HI=32767"
		echo 'dbLoadRecords("db/lia-real.db","'${xprams}'")'
		xprams="${cprams},T=REF_PHASE,LO=0,HI=1023"
		echo 'dbLoadRecords("db/lia-real.db","'${xprams}'")'
		xprams="${cprams},T=REF_SEQ_ID,LO=0,HI=$nrm1'")'
	done
fi


create_asyn_channel S14 127.0.0.1:4234	

if [ $MODE -ne 0 ]; then
	load_lia_aliases $ALIAS_DB2
fi




